[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "Zch"
name = "BettererLethalVRM"
versionNumber = "1.0.0"
description = "Replace player models with custom VRMs. Supports auto-blink and lip sync with automatic VRM expression detection."
websiteUrl = "https://github.com/Zch720/BettererLethalVRM"
containsNsfwContent = false

[package.dependencies]
# https://thunderstore.io/c/lethal-company/p/BepInEx/BepInExPack/
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE.md"
target = "LICENSE.md"

[[build.copy]]
source = "BettererLethalVRM/bin/Release/netstandard2.1/bundle.asset"
target = "BepInEx/plugins/Zch-BettererLethalVRM/bundle.asset"

[[build.copy]]
source = "BettererLethalVRM/bin/Release/netstandard2.1/FastSpringBone10.dll"
target = "BepInEx/plugins/Zch-BettererLethalVRM/FastSpringBone10.dll"

[[build.copy]]
source = "BettererLethalVRM/bin/Release/netstandard2.1/MToon.dll"
target = "BepInEx/plugins/Zch-BettererLethalVRM/MToon.dll"

[[build.copy]]
source = "BettererLethalVRM/bin/Release/netstandard2.1/Zch.BettererLethalVRM.deps.json"
target = "BepInEx/plugins/Zch-BettererLethalVRM/Zch.BettererLethalVRM.deps.json"

[[build.copy]]
source = "BettererLethalVRM/bin/Release/netstandard2.1/Zch.BettererLethalVRM.dll"
target = "BepInEx/plugins/Zch-BettererLethalVRM/Zch.BettererLethalVRM.dll"

[[build.copy]]
source = "BettererLethalVRM/bin/Release/netstandard2.1/UniGLTF.dll"
target = "BepInEx/plugins/Zch-BettererLethalVRM/UniGLTF.dll"

[[build.copy]]
source = "BettererLethalVRM/bin/Release/netstandard2.1/UniGLTF.Utils.dll"
target = "BepInEx/plugins/Zch-BettererLethalVRM/UniGLTF.Utils.dll"

[[build.copy]]
source = "BettererLethalVRM/bin/Release/netstandard2.1/UniHumanoid.dll"
target = "BepInEx/plugins/Zch-BettererLethalVRM/UniHumanoid.dll"

[[build.copy]]
source = "BettererLethalVRM/bin/Release/netstandard2.1/VRM10.dll"
target = "BepInEx/plugins/Zch-BettererLethalVRM/VRM10.dll"

[[build.copy]]
source = "BettererLethalVRM/bin/Release/netstandard2.1/VrmLib.dll"
target = "BepInEx/plugins/Zch-BettererLethalVRM/VrmLib.dll"

[[build.copy]]
source = "BettererLethalVRM/bin/Release/netstandard2.1/VRMShaders.GLTF.IO.Runtime.dll"
target = "BepInEx/plugins/Zch-BettererLethalVRM/VRMShaders.GLTF.IO.Runtime.dll"

[[build.copy]]
source = "BettererLethalVRM/bin/Release/netstandard2.1/VRMShaders.GLTF.UniUnlit.Runtime.dll"
target = "BepInEx/plugins/Zch-BettererLethalVRM/VRMShaders.GLTF.UniUnlit.Runtime.dll"

[[build.copy]]
source = "BettererLethalVRM/bin/Release/netstandard2.1/VRMShaders.VRM.IO.Runtime.dll"
target = "BepInEx/plugins/Zch-BettererLethalVRM/VRMShaders.VRM.IO.Runtime.dll"

[[build.copy]]
source = "BettererLethalVRM/bin/Release/netstandard2.1/VRMShaders.VRM10.Format.Runtime.dll"
target = "BepInEx/plugins/Zch-BettererLethalVRM/VRMShaders.VRM10.Format.Runtime.dll"

[[build.copy]]
source = "BettererLethalVRM/bin/Release/netstandard2.1/VRMShaders.VRM10.MToon10.Runtime.dll"
target = "BepInEx/plugins/Zch-BettererLethalVRM/VRMShaders.VRM10.MToon10.Runtime.dll"

[publish]
communities = ["lethal-company"]

[publish.categories]
# The categories are available at https://thunderstore.io near of the search bar
lethal-company = ["bepinex", "mods"]
